version: '3.3'
services:
        web:
                build:
                        context: ./php
                        dockerfile: Dockerfile
                container_name: php73release1
                volumes:
                        - ./php:/var/www/html/
                ports:
                        - 9001:80

                        
